spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/kdt-jpa;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
